### ISSUE TITLE
Create pre-workshop email for registrants

### ISSUE THREAD

**Issue by stephwright** [mozillascience/friendly-github#1]
Need to create text for pre-workshop survey including:
- [x] instructions to create GitHub account if don't already have one
- [x] pre-workshop survey
- [x] get registrant list from Yasmeen / Brianna

other info?

**Comment by stephwright** [comment]
Just emailed for the registrant list again.

**Comment by stephwright** [comment]
Received list will share separately.

**Comment by stephwright** [comment]
Created text for pre-workshop email [here](https://github.com/mozillascience/friendly-github/tree/master/TEMPLATES).
@daniellecrobinson @vantuyls @gallingerj please review

**Comment by daniellecrobinson** [comment]
@stephwright do we want a google form survey for the pre-workshop? Or some other format (survey monkey)? Am working on this now

**Comment by stephwright** [comment]
I'll ship it Monday. :shipit:

**Comment by stephwright** [comment]
Boomeranged to be sent out Monday.  All set.
