### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by stephwright** [mozillascience/friendly-github#11]
Use this one? https://science.mozilla.org/code-of-conduct

This one? https://github.com/mozillascience/open-data-training/blob/master/code-of-conduct.md

Other?

**Comment by vantuyls** [comment]
Either of these looks fine to me. Do we want to point this out as part of a workshop introduction (that's not on the agenda yet)?

**Comment by stephwright** [comment]
Was going to add to the pre-workshop email and point it out there... unless you think we need to go into it in the workshop.

**Comment by stephwright** [comment]
Turns out RDAP has it's own Code of Conduct.  Have added to index.html
