### ISSUE TITLE
Create pre-workshop assessment

### ISSUE THREAD

**Issue by stephwright** [mozillascience/friendly-github#2]
Here's the one we used for Joey's workshop: http://goo.gl/forms/pd9a356ZkJ
Others to pull from?

**Comment by stephwright** [comment]
Created template file [here](../blob/master/TEMPLATES/preassess.md)

Just some place to get started.

**Comment by daniellecrobinson** [comment]
@stephwright I have added to the document above, when you get a chance can you review? I'll make a draft google form in the meantime <3

**Comment by daniellecrobinson** [comment]
Here is a draft survey! Let me know what you think!
https://docs.google.com/forms/d/1Kq01tdT7qhesMZqAWZlKA6tbf_8pWPH39Rwi4clkVbI/edit?usp=sharing
