### ISSUE TITLE
Develop projects for folks to work on during gh-pages deep dive

### ISSUE THREAD

**Issue by stephwright** [mozillascience/friendly-github#23]
Look at etherpad for ideas.

**Comment by gallingerj** [comment]
Suggestion: if you have a Mozilla Science Lab project under construction (i.e. the [Open Data Training](https://github.com/mozillascience/open-data-training)) you could invite folks to create an issue, write markdown content for a module and generate a pull request, comment on an issue or commit to give feedback, etc. I know it's self-serving but I think it would actually be a really nice exercise. It mirrors our morning exercise and validates that this kind of work happens in the real world. You may end up with a mix of usable and unusable generated content. My only hesitation in suggesting this is that it may draw folks away from the gh-pages deep dive :stuck_out_tongue:

**Comment by stephwright** [comment]
I love that idea... @daniellecrobinson with the shift in how we're structuring the primers and instructor guides, do we want to go ahead and offer this up?
Could also provide general instructions on creating their own gh-pages website using the simple nterface.
Or have them start a new repo and create their CV?
Or have them create a To Do list or worklog?
Or plan their next travel?

**Comment by vantuyls** [comment]
or a project of projects.
