### ISSUE TITLE
These two sections could be combined?

### ISSUE THREAD

**Issue by daniellecrobinson** [mozillascience/friendly-github#25]
1. Hands on forking a repository & editing the README (15 mins)
2. Lingo Quiz
3. Small group work: Data Management Course Modules (30 mins)

Does the interface tour belong in the first one? Because this could all the the same exercise, with a lingo quiz break. Or the first one could be shorter, more of a demo. 

What do you think? @vantuyls @stephwright @gallingerj

**Comment by vantuyls** [comment]
i still don't see a place where we explicitely give an interface tour. maybe it belongs before the lingo quiz (Tour Github) followed by the quiz then the small group work including Hand on Forking etc.?

**Comment by stephwright** [comment]
Covered by @daniellecrobinson in Hands on forking exercise.
