### ISSUE TITLE
Set up To Dos Day Of

### ISSUE THREAD

**Issue by stephwright** [mozillascience/friendly-github#33]
- [x]  Set up +s & deltas for mid-workshop assessment
- [x] Launch Lingo Quiz
- [x] Tabs of examples on laptop
- [x] Nametags in different colors (instead of icebreaker labels)
- [x] Handout assessments at tables

**Comment by gallingerj** [comment]
Do we have two colours of sticky notes? And an etherpad to share URLs, notes during the workshop?

**Comment by stephwright** [comment]
Yep to both.  Stickies are in the back of my car w/ markers, nametags, pens, large post-it pads, post-it flip charts.
Etherpad is linked off the workshop website under "notes": https://public.etherpad-mozilla.org/p/sciencelab-RDAP2017-FriendlyGH
