### ISSUE TITLE
Create Lingo Quiz

### ISSUE THREAD

**Issue by stephwright** [mozillascience/friendly-github#4]
make better with Socrative: http://www.socrative.com/index.php

**Comment by gallingerj** [comment]
You can import the quiz using [this URL](https://b.socrative.com/teacher/#import-quiz/25989670).

**Comment by stephwright** [comment]
I will import the quiz and put in GH and we can all edit there.

**Comment by stephwright** [comment]
https://github.com/mozillascience/friendly-github/blob/master/assets/lingo-quiz.md

**Comment by stephwright** [comment]
Steph will find glossary and review for more questions.

**Comment by stephwright** [comment]
Found the glossary!!!  https://github.com/joeyklee/friendly-github-intro/blob/master/glossary.md

**Comment by stephwright** [comment]
Added a question 6 re: issues (and labels and milestones...).  Thoughts?  (It's still in the PR queue for discussion)
Also, thought Fork vs Clone might be a good discussion/challenge question at the end?

**Comment by stephwright** [comment]
Quiz created and available here: https://b.socrative.com/teacher/#import-quiz/28075840
