### ISSUE TITLE
Develop piece about gh-pages

### ISSUE THREAD

**Issue by stephwright** [mozillascience/friendly-github#6]
Existing resources: 
* https://www.thinkful.com/learn/a-guide-to-using-github-pages/
* http://jmcglone.com/guides/github-pages/
* https://pages.github.com/
* http://kbroman.org/simple_site/
* http://audreywatters.com/2013/07/07/how-to-run-your-site-on-github
* http://blog.revolunet.com/blog/2015/07/15/beautiful-static-website-in-minutes-with-github/

Command Line:
* http://blog.aquinzi.com/gh-pages-project/
* https://github.com/bmuellerhstat/gh-pages-tutorial
* http://learntocodewith.me/tutorials/github-pages/

**Comment by gallingerj** [comment]
As per our meeting yesterday, I can lead this part of the workshop. I'll have an outline and folks can follow along as I demo each step.

**Comment by gallingerj** [comment]
I've completed my notes for this section. Next step: I'd like to get feedback from the group (i.e. at our next meeting).
