### ISSUE TITLE
Identify examples

### ISSUE THREAD

**Issue by stephwright** [mozillascience/friendly-github#7]
#### Project mgmt:
- [ ] Managing tasks, assigning people to tasks, managing collaborations and groups
- [x] GitHub Projects - utility of project boards: https://github.com/daniellecrobinson/fellows-class-2016/projects/2
- [x] DAT:https://github.com/datproject
- [ ] OHSU Library: https://github.com/OHSU-Library
- [ ] OSU Library: https://github.com/orgs/osulp/teams
- [x] Mozilla Development Team?
- [ ] Workflow coordination  - DataRefuge : https://github.com/datarefuge

#### Ghpages:
- [x] https://mozillascience.github.io/WOW-2017/
- [x] https://github.com/vantuyls/studyGroup
- [ ] https://uoftcoders.github.io/studyGroup/
- [ ] http://gabano.github.io/studyGroup/

#### Gitbook:
- [ ] https://mozillascience.github.io/open-data-primers/

#### Code:
- [x] https://github.com/islandora

#### Open educational resources:
- [ ] NCIT C Programming: https://github.com/crackjack/ncit-c-programming
- [x] Software Carpentry: https://github.com/swcarpentry/swcarpentry
- [ ] Mozilla Open Data Training: https://github.com/mozillascience/open-data-training 
- [x] Open Science & Research Reproducibility: https://github.com/cbahlai/OSRR_course

#### Open data:
- [x] US Congress Legislators: https://github.com/unitedstates/congress-legislators
- [x] Open Addresses: https://github.com/openaddresses/openaddresses
- [x] Exoplanet Catalogue: https://github.com/OpenExoplanetCatalogue/open_exoplanet_catalogue

#### Projects:
- [x] Danielle's Project of Projects: https://github.com/daniellecrobinson/fellows-class-2016/projects/2
- [ ] An IA project: https://github.com/internetarchive/openlibrary/projects/1

**Comment by vantuyls** [comment]
**CV**
- [ ] https://github.com/smythp/cv

**Comment by stephwright** [comment]
Nice!  Thx for that example!
