### ISSUE TITLE
Create gh-pages for workshop website

### ISSUE THREAD

**Issue by stephwright** [mozillascience/friendly-github#9]
Include:
- [x] schedule
- [x] links to resources
  - [x] glossary
  - [x] markdown cheatsheet
  - [x] emoji cheatsheet
  - [x] slides
- [x] code of conduct
- [x] update workshop details

Use this template? https://mozillascience.github.io/WOW-2017/
https://github.com/mozillascience/WOW-2017

**Comment by gallingerj** [comment]
I'll create the gh-pages and we all can add content.

**Comment by gallingerj** [comment]
@stephwright Can you add me as a collaborator plz?

I cannot create the GH Pages without this status in the repo :smile_cat:

**Comment by stephwright** [comment]
So sorry @gallingerj ... thought I had already invited everyone as collaborator... have fixed that now.

**Comment by gallingerj** [comment]
Gracias @stephwright ! I've used the WOW-2017 as a template. In other words, I grabbed all of its files -- even the extraneous ones. A next step would be to go through and delete unnecessary files in the branch. And update the content in the index.html file, which is where most everything seems to live for the site.

**Comment by stephwright** [comment]
I THINK I removed all references to mozwow from index.html.  Did not clean up files in rest of repo yet.  Still need to add some stuff to index / cleanup.  Will create issues for them tomorrow.  Tired now. 💤

**Comment by gallingerj** [comment]
I deleted a bunch of extraneous folders + files from the repo. I kept a few non-essentials: the github folder, handouts/gitHub_for_collaboration.md + associated image files, and LICENSE.md, which may need updating.

My reasoning for keeping the github folder and handout materials was that it may be re-purposeable. There are some screenshots that may be worthwhile? And the glossary in the index.html file could be populated with the terms in the glossary in gitHub_for_collaboration.md

**Comment by stephwright** [comment]
Wholly onboard... thx @gallingerj !!!!

**Comment by stephwright** [comment]
Keep glossary ... perhaps use some terms for lingo quiz?

**Comment by stephwright** [comment]
Added glossary from original workshop w/ images for GH icons
